version: "3.9"

services:
  react-app:
    container_name: react_app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
