version: "3.9"

services:
  react-app:
    container_name: estudoorganizado-frontend
    build: .
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: npm run dev -- --host 0.0.0.0
